language: java
services: mongodb
sudo: false
jdk:
- oraclejdk8
env:
  - EDM=external
before_install:
- git submodule update --init --recursive
script: mvn install -D$EDM -B -V
notifications:
  email:
    recipients:
    - pir@csuc.cat
    on_success: always
    on_failure: always
  slack:
    secure: hCEEMfp/op6reZz+gZYXo8iwCPT6ec37QFxRRtxjh4Gky4p9RzPOBx+14zX3754Hg/xCYkVFyp7WB4cvzwo+JJOjvMPIoEGAja29lrl9HVdvP/M/trJWBJAU31WcX03q+kVvX5pkShgl1SzoKeE0c7ynuC8EzFh389xHnDmZ3T/4liA0td12mFTj/AOzS+OLxNEH2W6BQyEWiY2eid/7ELux9JUeLkiVBCz2IkrAodB8hoiCYOe1a4cDb5b6UikSrFX2wCkPRp/7zGLq9M942IhPjoT6FS32ab2eSlxz8vl91DtC5NsHtQB1sWNCxeqGUfyolUG3L2Ot4BSqawB40HYMcjUeIKV2gZWXU1+Bvci1YEObrJdL3Mjy+4HIaHuSO+OgZr13cllf/svrN5ERhM/XLfXT8eO1ddyiuLl9deZFgjgzksdiLu+rV3KEipoTFy5AZz5OpU2ipgPdjUkm2ckeSwQjdzVWFSropHG5Qq0b6nOvx9CtZZp4WTq1nW/WZ/2qoM8c5/SfUmWX08DDi1mOEzH7phNhV7Nh9B46apG5I3cNGanSHfFV53hMBfgDN9di/B01h4jd1nYSqX84vlfcaAOtQOccTFd4R+fyAkWsU1YPBK51HAHetb5K6uHen6GIUlKhe7YYLy46W2ZwYQ2PsdwUI5bWJ16C4hdeZFo=
